/*import net.darkhax.curseforgegradle.TaskPublishCurseForge*/

buildscript {
    repositories {
        flatDir {
            dirs '.'
        }
    }
    dependencies {
        classpath 'com.rikonardo.papermake:papermake:1.0.6'
    }
}

plugins {
    id 'java'
    id "com.modrinth.minotaur" version "2.9.0" // "2.+"
    /*id "net.darkhax.curseforgegradle" version "1.3.33"*/
}

apply plugin: 'com.rikonardo.papermake'
group = 'stranik.dev'
version = '1.2'

repositories {
    mavenCentral()
    gradlePluginPortal()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "placeholderapi"
        url = "https://repo.helpch.at/releases/"
    }
    maven {
        name = "phoenixdev"
        url = "https://nexus.phoenixdevt.fr/repository/maven-public/"
    }
}

ext {
    paperVer = findProperty('paperVer')  ?: '26.1'
}

dependencies {
    if (paperVer == '26.1.1' || paperVer == '26.1.2' || paperVer == '26.2')
        compileOnly "io.papermc.paper:paper-api:" + paperVer + ".build.+"
    else
        compileOnly "io.papermc.paper:paper-api:" + paperVer + "-R0.1-SNAPSHOT"

    compileOnly "me.clip:placeholderapi:2.12.3"
    compileOnly "io.lumine:MythicLib-dist:1.7.1-SNAPSHOT"
}

def targetJavaVersion = (paperVer == '26.1.1' || paperVer == '26.1.2' || paperVer == '26.2') ? 25 : 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [
        version: version,
        paperVer: project.ext.paperVer
    ]
    inputs.properties props
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

tasks.named('jar', Jar) {
    archiveClassifier.set(paperVer)
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = 'YvIMTGRf'
    versionName = "NametagHider v${version}"
    versionNumber = "${version}"
    versionType = "release"
    changelog = pluginChangelog
    uploadFile = tasks.jar.archiveFile.get().asFile
    gameVersions = [paperVer]
    loaders = ['paper']
    dependencies {
        optional.project('lKEzGugV')
    }
}

/*tasks.register('publishCurseForge', TaskPublishCurseForge) {
    // ВАЖНО: Новый API CurseForge требует именно этот токен
    apiToken = System.getenv("CURSEFORGE_TOKEN") ?: ""

    def projectId = '1350069'
    def mainFile = upload(projectId, jar)

    mainFile.displayName = "NametagHider v${version}-${paperVer}"
    mainFile.releaseType = 'release'
    mainFile.changelog = findProperty('pluginChangelog') ?: ''

    mainFile.addGameVersion('Paper')
    mainFile.addGameVersion(paperVer)
    mainFile.addOptional('protocollib')
}

gradle.taskGraph.whenReady {
    if (gradle.taskGraph.hasTask(":publishCurseForge") && !System.getenv("CURSEFORGE_TOKEN")) {
        throw new Exception("CurseForge token не найден. Задайте ENV переменную CURSEFORGE_TOKEN")
    }
}*/

gradle.taskGraph.whenReady {
    if (!modrinth.token.isPresent()) {
        throw new Exception("Modrinth token не найден. Задайте -PmodrinthToken или \$ENV:MODRINTH_TOKEN")
    }
}

def isWindows = System.getProperty('os.name').toLowerCase().contains('windows')
def gradlew = isWindows ? 'gradlew.bat' : './gradlew'

tasks.register('uploadAllOneVer') {
    group = 'upload'
    description = 'Загружает Bukkit, Spigot и Paper JAR'
    dependsOn 'build'

    finalizedBy 'modrinth'
    // finalizedBy 'modrinth', 'publishCurseForge'
}

tasks.register('buildAll') {
    group = 'build'
    description = 'Собирает JAR под все версии из paperMatrix'

    doLast {
        def versions = (findProperty('paperMatrix') ?: '')
                .toString()
                .split(',')
                .collect { it.trim() }
                .findAll { !it.isEmpty() }

        if (versions.isEmpty()) {
            throw new Exception("Добавьте paperMatrix в gradle.properties, например: paperMatrix=1.21,1.21.1,...,1.21.8")
        }

        def execOperations = services.get(ExecOperations)

        versions.each { ver ->
            println "==> Build for Paper ${ver}"

            execOperations.exec {
                workingDir = rootDir
                commandLine gradlew, 'build', "-PpaperVer=${ver}"
            }
        }
    }
}

tasks.register('uploadAll') {
    group = 'upload'
    description = 'Собирает JAR под все версии из paperMatrix'

    doLast {
        def versions = (findProperty('paperMatrix') ?: '')
                .toString()
                .split(',')
                .collect { it.trim() }
                .findAll { !it.isEmpty() }

        if (versions.isEmpty()) {
            throw new Exception("Добавьте paperMatrix в gradle.properties, например: paperMatrix=1.21,1.21.1,...,1.21.8")
        }

        def execOperations = services.get(ExecOperations)

        versions.each { ver ->
            println "==> Upload for Paper ${ver}"

            execOperations.exec {
                workingDir = rootDir
                commandLine gradlew, 'uploadAllOneVer', "-PpaperVer=${ver}"
            }
        }
    }
}