plugins {
    id 'java'
    id "com.modrinth.minotaur" version "2.+"
}

group = 'stranik.dev'
version = '1.0'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT"
}

ext {
    paperVer = findProperty('paperVer')  ?: '1.21'
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

tasks.named('jar') {
    archiveClassifier.set(paperVer)
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = 'YvIMTGRf'
    versionName = "NametagHider v${version}"
    versionNumber = "${version}"
    versionType = "release"
    changelog = ''
    uploadFile = tasks.jar.archiveFile.get().asFile
    gameVersions = [paperVer]
    loaders = ['paper']
}

gradle.taskGraph.whenReady {
    if (!modrinth.token.isPresent()) {
        throw new Exception("Modrinth token не найден. Задайте -PmodrinthToken или \$ENV:MODRINTH_TOKEN")
    }
}

def isWindows = System.getProperty('os.name').toLowerCase().contains('windows')
def gradlew = isWindows ? 'gradlew.bat' : './gradlew'

tasks.register('uploadAllOneVer') {
    group = 'upload'
    description = 'Загружает Bukkit, Spigot и Paper JAR'
    dependsOn 'build'

    finalizedBy 'modrinth'
}

tasks.register('buildAll') {
    group = 'build'
    description = 'Собирает JAR под все версии из paperMatrix'

    doLast {
        def versions = (findProperty('paperMatrix') ?: '')
                .toString()
                .split(',')
                .collect { it.trim() }
                .findAll { !it.isEmpty() }

        if (versions.isEmpty()) {
            throw new Exception("Добавьте paperMatrix в gradle.properties, например: paperMatrix=1.21,1.21.1,...,1.21.8")
        }

        versions.each { ver ->
            println "==> Build for Paper ${ver}"
            def result = exec {
                workingDir rootDir
                commandLine gradlew, 'build', "-PpaperVer=${ver}"
                standardOutput = System.out
                errorOutput = System.err
            }
        }
    }
}

tasks.register('uploadAll') {
    group = 'upload'
    description = 'Собирает JAR под все версии из paperMatrix'

    doLast {
        def versions = (findProperty('paperMatrix') ?: '')
                .toString()
                .split(',')
                .collect { it.trim() }
                .findAll { !it.isEmpty() }

        if (versions.isEmpty()) {
            throw new Exception("Добавьте paperMatrix в gradle.properties, например: paperMatrix=1.21,1.21.1,...,1.21.8")
        }

        versions.each { ver ->
            println "==> Upload for Paper ${ver}"
            def result = exec {
                workingDir rootDir
                commandLine gradlew, 'uploadAllOneVer', "-PpaperVer=${ver}"
                standardOutput = System.out
                errorOutput = System.err
            }
        }
    }
}