name: NametagHiderPlugin
version: '${version}'
main: stranik.dev.nametaghider.NametagHiderPlugin
api-version: '${paperVer}'
softdepend: [PlaceholderAPI]

commands:
  hide_nametag:
    permission: nametagHider.commands
    